version: "1.0"
info:
  model: int-scaffold
packages:
- name: AlexDADADemoProject
  gitServerName: AlexGit
  gitUrl: https://github.com/AlexFoo95/AlexDADADemoProject
  gitUsername: AlexFoo95
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.softwareag.com
  wpmRegistry: softwareag
- name: PIE-87920
  version: "1.0"
  gitServerName: ArthurGithub
  gitUrl: https://github.com/agohpc
  gitUsername: agohpc
  gitBranch: master
- name: AlexDADAGitProject
  version: "1.0"
  gitServerName: AlexGit
  gitUrl: https://github.com/AlexFoo95
  gitUsername: AlexFoo95
  gitBranch: master
- name: AlexDADAGit2Project
  version: "1.0"
  gitServerName: AlexGit
  gitUrl: https://github.com/AlexFoo95
  gitUsername: AlexFoo95
  gitBranch: master
- name: OpenWeatherClient
  version: "1.0"
  gitServerName: RAHS_Not_SAG
  gitUrl: https://github.com/rahuldemocenter
  gitUsername: rahuldemocenter
  gitBranch: main
services:
- serviceName: project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Demo_Employee
  packages:
  - name: AlexDADADemoProject
    version: "1.0"
- serviceName: project.alexdadademo.integrations:DADAEmployeeSelect
  packages:
  - name: AlexDADADemoProject
    version: "1.0"
- serviceName: project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DADA_Employee_Select
  packages:
  - name: AlexDADADemoProject
    version: "1.0"
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: project.alexdadademo.integrations:OpenWeatherTest
  packages:
  - name: AlexDADADemoProject
    version: "1.0"
  - name: OpenWeatherClient
    version: "1.0"
- serviceName: OpenWeatherClient.REST.openweatherclient_.services:CurrentWeatherData
  packages:
  - name: OpenWeatherClient
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.json:jsonStreamToDocument
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.json:documentToJSONString
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: project.alexdadademo.integrations:GitTesting
  packages:
  - name: AlexDADADemoProject
    version: "1.0"
  - name: AlexDADAGitProject
    version: "1.0"
  - name: OpenWeatherClient
    version: "1.0"
  - name: PIE-87920
    version: "1.0"
- serviceName: GitTest:GitTest
  packages:
  - name: AlexDADAGitProject
    version: "1.0"
- serviceName: project.alexdadademo.integrations:pkg
  packages:
  - name: AlexDADADemoProject
    version: "1.0"
  - name: AlexDADAGitProject
    version: "1.0"
  - name: AlexDADAGit2Project
    version: "1.0"
  - name: PIE-87920
    version: "1.0"
  - name: OpenWeatherClient
    version: "1.0"
- serviceName: jsonSchemaTest:schemaTesting
  packages:
  - name: PIE-87920
    version: "1.0"
- serviceName: pub.json.schema:validate
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: project.alexdadademo.integrations:t
  packages:
  - name: AlexDADADemoProject
    version: "1.0"
  - name: AlexDADAGitProject
    version: "1.0"
  - name: AlexDADAGit2Project
    version: "1.0"
  - name: PIE-87920
    version: "1.0"
  - name: OpenWeatherClient
    version: "1.0"
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
configurationVariables:
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionSettings.trustStore
  : ""
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionSettings.driverType
  : MSSQL
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionManagerSettings.startupBackoffSecs
  : "10"
  jdbc.jdbcTestPool.expireTime: "60000"
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionManagerSettings.maximumPoolSize
  : "10"
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionSettings.datasourceClass
  : com.microsoft.sqlserver.jdbc.SQLServerDataSource
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionManagerSettings.blockingTimeout
  : "1000"
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionSettings.serverName
  : SAG-H9GTVL3
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionSettings.password
  : "{AES}aYrXC43dTWsDUHRWG5mhTA=="
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionSettings.dbType
  : MSSQL
  jdbc.jdbcTestPool.spyenabled: "false"
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionSettings.networkProtocol
  : ""
  jdbc.jdbcTestPool.snoopenabled: "false"
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionEnabled
  : "false"
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionSettings.databaseName
  : Demo
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionManagerSettings.minimumPoolSize
  : "0"
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionSettings.keyStore
  : ""
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionSettings.portNumber
  : "1433"
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionSettings.user
  : Administrator
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionManagerSettings.poolable
  : "false"
  ? artConnection.AlexDADADemoProject.project.alexdadademo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Demo_Employee.connectionManagerSettings.startupRetryCount
  : "0"
  jdbc.jdbcTestPool.useSSL: "false"
